exclude:
- README.md

gems:
  - jekyll-sitemap
  - jemoji

timezone: Europe/Berlin

title: Wurst Client

paginate: 5

paginate_path: "/news-:num/"

permalink: /news/:year-:month-:day-:title/

excerpt_separator: <!--read more-->

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Alexander01998
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alexander01998
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
