exclude:
- README.md

gems:
  - jekyll-sitemap
  - jemoji

timezone: Europe/Berlin

title: Wurst Client

paginate: 5

paginate_path: "/news/:num"

permalink: /news/:year-:month-:day-:title/index.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Alexander01998"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Alexander01998"
      layout: "post"
