exclude:
- README.md
- start.bat

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/Berlin

title: Wurst-Client.tk

paginate: 10

paginate_path: "/news/:num/"

permalink: /news/:year-:month-:day-:title/

excerpt_separator: <!--read more-->

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  questions:
    output: true
    permalink: /faq/:slug/
  redirects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Alexander01998
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alexander01998
      secondarytitle: Wurst News
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
      secondarytitle: Wurst Wiki
  - scope:
      path: ""
      type: questions
    values:
      layout: question
      secondarytitle: Wurst FAQ
      category: Miscellaneous
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirect
