exclude:
- start.bat

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/Berlin

title: WurstClient.net

mcversions:
  "1.11": "1.11 - 1.11.2"
  "1.10": "1.10 - 1.10.2"
  "1.9.4": "1.9 - 1.9.2"
  "1.8": "1.8 - 1.8.9"

paginate: 10
paginate_path: "/news/:num/"
permalink: /news/:year-:month-:day-:title/
excerpt_separator: <!--read more-->

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:slug/
  redirects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Alexander01998
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alexander01998
      secondarytitle: Wurst News
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
      secondarytitle: Wurst Wiki
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirect
